title:  Graficaci贸n - Documentaci贸n
description: Apuntes y pr谩cticas del curso de Graficaci贸n

# Tema oscuro fijo
remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown

# Navegaci贸n m铆nima (opcional)
nav:
  - name: Inicio
    link: /
  - name: Documentaci贸n
    link: /docs/
  - name: Repositorio
    link: https://github.com/docpoosersel/Graficacion-Documentacion

